// Code generated by protoc-gen-go.
// source: gamemsg.proto
// DO NOT EDIT!

/*
Package gameproto is a generated protocol buffer package.

It is generated from these files:
	gamemsg.proto
	login.proto

It has these top-level messages:
	ProtoMsg
	Cluster_UpdateInfoNotify
	LoginSvr_LoginReq
	LoginSvr_LoginResp
*/
package gameproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 定义消息ID
type MsgID int32

const (
	MsgID_MSGID_INVALID MsgID = 0
	// 系统消息ID
	MsgID_CLUSTER_UPDATEINFO_NOTIFY MsgID = 1
	// 登录服务消息ID
	MsgID_LOGINSVR_LOGIN_REQ  MsgID = 30
	MsgID_LOGINSVR_LOGIN_RESP MsgID = 31
)

var MsgID_name = map[int32]string{
	0:  "MSGID_INVALID",
	1:  "CLUSTER_UPDATEINFO_NOTIFY",
	30: "LOGINSVR_LOGIN_REQ",
	31: "LOGINSVR_LOGIN_RESP",
}
var MsgID_value = map[string]int32{
	"MSGID_INVALID":             0,
	"CLUSTER_UPDATEINFO_NOTIFY": 1,
	"LOGINSVR_LOGIN_REQ":        30,
	"LOGINSVR_LOGIN_RESP":       31,
}

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}
func (x MsgID) String() string {
	return proto.EnumName(MsgID_name, int32(x))
}
func (x *MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgID_value, data, "MsgID")
	if err != nil {
		return err
	}
	*x = MsgID(value)
	return nil
}
func (MsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 客户端服务器通信的消息
type ProtoMsg struct {
	Msgid            *MsgID  `protobuf:"varint,1,opt,name=msgid,enum=gameproto.MsgID" json:"msgid,omitempty"`
	Uin              *uint32 `protobuf:"varint,2,opt,name=uin" json:"uin,omitempty"`
	Msgdata          []byte  `protobuf:"bytes,3,opt,name=msgdata" json:"msgdata,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoMsg) Reset()                    { *m = ProtoMsg{} }
func (m *ProtoMsg) String() string            { return proto.CompactTextString(m) }
func (*ProtoMsg) ProtoMessage()               {}
func (*ProtoMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoMsg) GetMsgid() MsgID {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return MsgID_MSGID_INVALID
}

func (m *ProtoMsg) GetUin() uint32 {
	if m != nil && m.Uin != nil {
		return *m.Uin
	}
	return 0
}

func (m *ProtoMsg) GetMsgdata() []byte {
	if m != nil {
		return m.Msgdata
	}
	return nil
}

// 集群信息通知，对应CLUSTER_UPDATEINFO_NOTIFY
type Cluster_UpdateInfoNotify struct {
	LocalendID       *int32 `protobuf:"varint,1,opt,name=localendID" json:"localendID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Cluster_UpdateInfoNotify) Reset()                    { *m = Cluster_UpdateInfoNotify{} }
func (m *Cluster_UpdateInfoNotify) String() string            { return proto.CompactTextString(m) }
func (*Cluster_UpdateInfoNotify) ProtoMessage()               {}
func (*Cluster_UpdateInfoNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Cluster_UpdateInfoNotify) GetLocalendID() int32 {
	if m != nil && m.LocalendID != nil {
		return *m.LocalendID
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoMsg)(nil), "gameproto.ProtoMsg")
	proto.RegisterType((*Cluster_UpdateInfoNotify)(nil), "gameproto.Cluster_UpdateInfoNotify")
	proto.RegisterEnum("gameproto.MsgID", MsgID_name, MsgID_value)
}

func init() { proto.RegisterFile("gamemsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0xcc, 0x4f, 0x4f, 0xb3, 0x40,
	0x10, 0xc7, 0xf1, 0x87, 0xa7, 0x21, 0xea, 0x28, 0x8a, 0x63, 0xa2, 0x78, 0xd0, 0x92, 0x9e, 0x88,
	0x07, 0x0e, 0xbe, 0x83, 0xa6, 0xd0, 0x66, 0x12, 0x58, 0x90, 0x3f, 0x4d, 0x3c, 0x6d, 0x36, 0x42,
	0x37, 0x18, 0x60, 0x9b, 0xee, 0xf6, 0xe0, 0xbb, 0x37, 0xc5, 0xc4, 0x8b, 0xb7, 0xcf, 0x4c, 0x7e,
	0xf9, 0x82, 0x23, 0xc5, 0xd0, 0x0e, 0x5a, 0x86, 0xfb, 0x83, 0x32, 0x0a, 0x2f, 0x4e, 0xe7, 0xc4,
	0x05, 0xc1, 0x79, 0x7e, 0x42, 0xaa, 0x25, 0xce, 0xc1, 0x1e, 0xb4, 0xec, 0x1a, 0xcf, 0xf2, 0xad,
	0xe0, 0xfa, 0xd5, 0x0d, 0x7f, 0x67, 0x61, 0xaa, 0x25, 0x45, 0x78, 0x09, 0xb3, 0x63, 0x37, 0x7a,
	0xff, 0x7d, 0x2b, 0x70, 0xf0, 0x06, 0xce, 0x06, 0x2d, 0x1b, 0x61, 0x84, 0x37, 0xf3, 0xad, 0xe0,
	0x6a, 0x11, 0x82, 0xb7, 0xea, 0x8f, 0xda, 0xb4, 0x07, 0x5e, 0xef, 0x1b, 0x61, 0x5a, 0x1a, 0x77,
	0x8a, 0x29, 0xd3, 0xed, 0xbe, 0x10, 0x01, 0x7a, 0xf5, 0x21, 0xfa, 0x76, 0x6c, 0x28, 0x9a, 0xfa,
	0xf6, 0xcb, 0x27, 0xd8, 0x3f, 0xd9, 0x5b, 0x70, 0xd2, 0x72, 0x43, 0x11, 0x27, 0xb6, 0x5d, 0x26,
	0x14, 0xb9, 0xff, 0xf0, 0x09, 0x1e, 0x57, 0x49, 0x5d, 0x56, 0x71, 0xc1, 0xeb, 0x3c, 0x5a, 0x56,
	0x31, 0xb1, 0x75, 0xc6, 0x59, 0x56, 0xd1, 0xfa, 0xdd, 0xb5, 0xf0, 0x1e, 0x30, 0xc9, 0x36, 0xc4,
	0xca, 0x6d, 0xc1, 0x27, 0xf0, 0x22, 0x7e, 0x73, 0x9f, 0xf1, 0x01, 0xee, 0xfe, 0xfc, 0xcb, 0xdc,
	0x9d, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x0b, 0xa5, 0x6d, 0x01, 0x01, 0x00, 0x00,
}
