// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package gameproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 登录请求，对应LOGINSVR_LOGIN_REQ
type LoginSvr_LoginReq struct {
	Uin              *uint32 `protobuf:"varint,1,opt,name=uin" json:"uin,omitempty"`
	StrSessionKey    *string `protobuf:"bytes,2,opt,name=strSessionKey" json:"strSessionKey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginSvr_LoginReq) Reset()                    { *m = LoginSvr_LoginReq{} }
func (m *LoginSvr_LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginSvr_LoginReq) ProtoMessage()               {}
func (*LoginSvr_LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *LoginSvr_LoginReq) GetUin() uint32 {
	if m != nil && m.Uin != nil {
		return *m.Uin
	}
	return 0
}

func (m *LoginSvr_LoginReq) GetStrSessionKey() string {
	if m != nil && m.StrSessionKey != nil {
		return *m.StrSessionKey
	}
	return ""
}

// 登录返回
type LoginSvr_LoginResp struct {
	IResult          *int32 `protobuf:"varint,1,opt,name=iResult" json:"iResult,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginSvr_LoginResp) Reset()                    { *m = LoginSvr_LoginResp{} }
func (m *LoginSvr_LoginResp) String() string            { return proto.CompactTextString(m) }
func (*LoginSvr_LoginResp) ProtoMessage()               {}
func (*LoginSvr_LoginResp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *LoginSvr_LoginResp) GetIResult() int32 {
	if m != nil && m.IResult != nil {
		return *m.IResult
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginSvr_LoginReq)(nil), "gameproto.LoginSvr_LoginReq")
	proto.RegisterType((*LoginSvr_LoginResp)(nil), "gameproto.LoginSvr_LoginResp")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x4f, 0xcc, 0x4d, 0x05, 0x33, 0x95,
	0xcc, 0xb9, 0x04, 0x7d, 0x40, 0x32, 0xc1, 0x65, 0x45, 0xf1, 0x60, 0x46, 0x50, 0x6a, 0xa1, 0x10,
	0x37, 0x17, 0x73, 0x69, 0x66, 0x9e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xaf, 0x90, 0x28, 0x17, 0x6f,
	0x71, 0x49, 0x51, 0x70, 0x6a, 0x71, 0x71, 0x66, 0x7e, 0x9e, 0x77, 0x6a, 0xa5, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0xa7, 0x92, 0x2a, 0x97, 0x10, 0xba, 0xc6, 0xe2, 0x02, 0x21, 0x7e, 0x2e, 0xf6, 0xcc,
	0xa0, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0xb0, 0x6e, 0x56, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba,
	0x40, 0xb7, 0x0d, 0x78, 0x00, 0x00, 0x00,
}
