// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package gameproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 登录请求，对应LOGINSVR_LOGIN_REQ
// todo jasonxiong 暂时使用账号密码登录，后续根据对接的平台修改
type LoginSvr_LoginReq struct {
	StrAccount       *string `protobuf:"bytes,1,opt,name=strAccount" json:"strAccount,omitempty"`
	StrPasswd        *string `protobuf:"bytes,2,opt,name=strPasswd" json:"strPasswd,omitempty"`
	IAccType         *int32  `protobuf:"varint,3,opt,name=iAccType" json:"iAccType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginSvr_LoginReq) Reset()                    { *m = LoginSvr_LoginReq{} }
func (m *LoginSvr_LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginSvr_LoginReq) ProtoMessage()               {}
func (*LoginSvr_LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *LoginSvr_LoginReq) GetStrAccount() string {
	if m != nil && m.StrAccount != nil {
		return *m.StrAccount
	}
	return ""
}

func (m *LoginSvr_LoginReq) GetStrPasswd() string {
	if m != nil && m.StrPasswd != nil {
		return *m.StrPasswd
	}
	return ""
}

func (m *LoginSvr_LoginReq) GetIAccType() int32 {
	if m != nil && m.IAccType != nil {
		return *m.IAccType
	}
	return 0
}

// 登录返回,对应LOGINSVR_LOGIN_RESP
type LoginSvr_LoginResp struct {
	IResult          *int32  `protobuf:"varint,1,opt,name=iResult" json:"iResult,omitempty"`
	StrSessionKey    *string `protobuf:"bytes,2,opt,name=strSessionKey" json:"strSessionKey,omitempty"`
	StrLoginInfo     *string `protobuf:"bytes,3,opt,name=strLoginInfo" json:"strLoginInfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginSvr_LoginResp) Reset()                    { *m = LoginSvr_LoginResp{} }
func (m *LoginSvr_LoginResp) String() string            { return proto.CompactTextString(m) }
func (*LoginSvr_LoginResp) ProtoMessage()               {}
func (*LoginSvr_LoginResp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *LoginSvr_LoginResp) GetIResult() int32 {
	if m != nil && m.IResult != nil {
		return *m.IResult
	}
	return 0
}

func (m *LoginSvr_LoginResp) GetStrSessionKey() string {
	if m != nil && m.StrSessionKey != nil {
		return *m.StrSessionKey
	}
	return ""
}

func (m *LoginSvr_LoginResp) GetStrLoginInfo() string {
	if m != nil && m.StrLoginInfo != nil {
		return *m.StrLoginInfo
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginSvr_LoginReq)(nil), "gameproto.LoginSvr_LoginReq")
	proto.RegisterType((*LoginSvr_LoginResp)(nil), "gameproto.LoginSvr_LoginResp")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0xcc, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0xc6, 0x71, 0xaa, 0x14, 0xcd, 0xa9, 0x68, 0x0f, 0x85, 0x8e, 0xa5, 0x53, 0x27, 0xdf, 0xa1,
	0xa3, 0xd8, 0x41, 0x5a, 0x77, 0x29, 0x31, 0x96, 0x40, 0x4d, 0x62, 0xee, 0xaa, 0xf4, 0xed, 0xc5,
	0xe8, 0xe4, 0xf6, 0xe7, 0x8e, 0xef, 0x07, 0x8b, 0xde, 0x76, 0xda, 0xec, 0x9d, 0xb7, 0x6c, 0x51,
	0x74, 0xed, 0x5d, 0x85, 0xcc, 0x2b, 0x48, 0xaa, 0xcf, 0xa7, 0x79, 0xfa, 0x4b, 0x88, 0x5a, 0x3d,
	0x10, 0x01, 0x88, 0x7d, 0x29, 0xa5, 0x1d, 0x0c, 0xa7, 0x51, 0x16, 0x15, 0x02, 0x13, 0x10, 0xc4,
	0xfe, 0xd4, 0x12, 0xbd, 0xae, 0xe9, 0x24, 0x9c, 0x36, 0x30, 0xd7, 0xa5, 0x94, 0xe7, 0xd1, 0xa9,
	0x74, 0x9a, 0x45, 0x45, 0x9c, 0xd7, 0x80, 0xff, 0x1a, 0x39, 0x5c, 0xc3, 0x4c, 0xd7, 0x8a, 0x86,
	0xfe, 0x6b, 0xc5, 0xb8, 0x83, 0x15, 0xb1, 0x6f, 0x14, 0x91, 0xb6, 0xe6, 0xa8, 0xc6, 0x9f, 0xb7,
	0x85, 0x25, 0xb1, 0x0f, 0xbb, 0x83, 0xb9, 0xd9, 0x60, 0x8a, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa0, 0xde, 0xdc, 0x68, 0xba, 0x00, 0x00, 0x00,
}
